version: '3'
services:
  prisma-2-postgres:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - prisma-2-postgres:/var/lib/postgresql/data
volumes:
  prisma-2-postgres: